server:
  port: 9999

spring:
  application:
    name: yueyun-base-job
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: your-email@qq.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# XXL-JOB配置
xxl:
  job:
    admin-addresses: http://xxl-job-admin:8080/xxl-job-admin
    executor:
      appname: yueyun-base-job
      address: 
      ip: 
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token 